import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/schemas/sanity-utils';

export const metadata = {
  title: 'Or Kon Portfolio',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="lg:max-w-none md:max-w-3xl mx-auto py-10 px-8">
        <header className="flex items-center justify-between">
          <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">
            <p className='xl:text-3xl lg:text-2xl'>OrKon</p>
            </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                 <p className='xl:text-xl lg:text-lg'>
                  {page.title}
                 </p>
                </Link>
            ))}

          </div>

        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  )
}
